// Fixed OMP original-source fixtures. Expected results are never Rust-derived.
import * as fs from 'node:fs';
import * as path from 'node:path';
import { Database } from 'bun:sqlite';

const spec=(id,extra={})=>({id,name:`Name ${id}`,api:'openai-completions',provider:'test',baseUrl:'https://fixture.test/v1',reasoning:false,input:['text'],cost:{input:1,output:2,cacheRead:.1,cacheWrite:0},contextWindow:128000,maxTokens:8192,...extra});
const raw=value=>({value});
const failed={error:{name:'Error',message:'fixture failure'}};

export async function fixtures(api){
 const openai=await api.load('provider-models/openai-compat');
 const special=await api.load('provider-models/special');
 const cline=await api.load('provider-models/cline-pass');
 const descriptors=await api.load('provider-models/descriptors');
 const materialized={sourceCommit:'596f2da7101178214aa27a753529d15e6b7ad91d',modules:{}};
 for(const[name,module]of [['openai-compat',openai],['special',special],['cline-pass',cline]]){
  const constants={};for(const[key,value]of Object.entries(module))if(typeof value!=='function'&&(Array.isArray(value)||value&&typeof value==='object'))constants[key]=api.encode(value);
  materialized.modules[name]=constants;
 }
 materialized.catalogProviders=api.encode(descriptors.CATALOG_PROVIDERS.map(({createModelManagerOptions,...entry})=>({...entry,hasFactory:typeof createModelManagerOptions==='function'})));
 fs.writeFileSync(path.join(api.root,'provider-static-native.json'),JSON.stringify(materialized));
 const cases=[];const add=(id,options,extra={})=>cases.push({id:`manager/${id}`,family:'manager',module:'model-manager',op:'resolveProviderModels',options,responses:[],...extra});
 const base={providerId:'test',staticModels:[spec('a')],now:1000000};
 add('static-only',base);add('offline-failure',base,{dynamic:[failed],steps:[{strategy:'offline'}]});
 add('dynamic-success',base,{dynamic:[raw([spec('b'),spec('a',{name:' Remote A ',reasoning:true,input:['text','image'],cost:{input:4,output:0,cacheRead:-1,cacheWrite:2},contextWindow:4096,maxTokens:4096})])]});
 add('dynamic-primitive',base,{dynamic:[raw(42)]});add('dynamic-undefined',base,{dynamic:[{undefined:true}]});add('dynamic-null',base,{dynamic:[raw(null)]});add('dynamic-throw',base,{dynamic:[failed]});
 add('dynamic-authority-empty',{...base,dynamicModelsAuthoritative:true},{dynamic:[raw([]),raw([spec('b')])],steps:[{}, {now:1000100}, {now:1300000}]});
 add('dynamic-authority-prune',{...base,dynamicModelsAuthoritative:true},{dynamic:[raw([spec('b')])]});
 add('empty-nonauthority-retry',base,{dynamic:[raw([]),raw([spec('b')])],steps:[{}, {now:1000010}, {now:1300000}]});
 add('models-dev-empty',base,{modelsDev:[{payload:5,mapped:[]}],steps:[{},{}]});
 add('models-dev-map-throw',base,{modelsDev:[{payload:{},mapError:failed.error}]});
 add('models-dev-map-null',base,{modelsDev:[{payload:null,mapped:null}]});
 add('sources-parallel',base,{dynamic:[raw([spec('a',{name:'Dynamic'})])],modelsDev:[{payload:8,mapped:[spec('a',{name:'Catalog'}),spec('b')]}]});
 add('dynamic-fails-dev-success',base,{dynamic:[failed],modelsDev:[{payload:{},mapped:[spec('b')]}],cache:{models:[spec('c')],authoritative:true,updatedAt:800000,matchingFingerprint:true}});
 add('dynamic-authority-dev-fails',{...base,dynamicModelsAuthoritative:true},{dynamic:[raw([spec('b')])],modelsDev:[{error:failed.error}],cache:{models:[spec('c')],authoritative:true,updatedAt:800000,matchingFingerprint:true}});
 add('dev-additive-static-metadata',{...base,additiveOnly:true},{modelsDev:[{payload:{},mapped:[spec('a',{name:'Must not override',contextWindow:900000,int:42,tps:9}),spec('b')]}]});
 for(const[provider,extra]of [['test',{}],['github-copilot',{}],['deepinfra',{}],['synthetic',{reasoning:true}]])add(`merge-${provider}`,{...base,providerId:provider,staticModels:[spec('a',{provider,reasoning:true,input:['text','image']})]},{dynamic:[raw([spec('a',{provider,...extra})])]});
 add('merge-endpoint-change',base,{dynamic:[raw([spec('a',{baseUrl:'https://other.test',input:['text']})])]});
 add('merge-own-undefined',base,{dynamic:[{encoded:api.encode([spec('a',{compat:undefined,headers:undefined,contextPromotionTarget:undefined})])}]});
 add('merge-name-is-id',base,{dynamic:[raw([spec('a',{name:' a '})])]});
 add('merge-authored-compat',{...base,staticModels:[spec('a',{compat:{supportsStore:false}})]},{dynamic:[raw([spec('a',{compat:{supportsDeveloperRole:false}})])]});
 add('duplicate-position',{...base,staticModels:[spec('z'),spec('a'),spec('z',{name:'Last z'})]},{dynamic:[raw([spec('a',{name:'Last a'}),spec('b')])]});
 add('normalization-native',base,{dynamic:[{encoded:api.encode([spec('finite',{contextWindow:null,maxTokens:null}),spec('nan',{cost:{input:NaN,output:2,cacheRead:0,cacheWrite:0}}),spec('infinite',{maxTokens:Infinity}),spec('negative',{cost:{input:-2,output:-1,cacheRead:0,cacheWrite:0}}),spec('badlong',{cost:{input:0,output:0,cacheRead:0,cacheWrite:0,longContext:null}}),spec('undefined',{maxTokens:undefined}),null,42,[],{},spec('\ud800',{name:'\udc00'})])}]});
 const invalids=[['empty-id',{id:''}],['empty-name',{name:''}],['empty-provider',{provider:''}],['empty-url',{baseUrl:''}],['empty-api',{api:''}],['bool-reasoning',{reasoning:1}],['empty-input',{input:[]}],['unknown-input',{input:['audio']}],['negative-limit',{contextWindow:-1}],['zero-limit',{maxTokens:0}],['undefined-cost',{cost:{input:1,output:2,cacheRead:0}}]];
 for(const[id,extra]of invalids)add(`guard-${id}`,base,{dynamic:[raw([spec('invalid',extra)])]});
 for(const[strategy,age,authoritative]of [['offline',8000000,true],['online',1,true],['online-if-uncached',1,true],['online-if-uncached',1,false],['online-if-uncached',300000,false],['online-if-uncached',7200001,true]])add(`cache-${strategy}-${age}-${authoritative}`,base,{dynamic:[raw([spec('b')])],cache:{models:[spec('c')],authoritative,updatedAt:1000000-age,matchingFingerprint:true},steps:[{strategy}]});
 add('migration-drop',{...base,dropCachedModelIdsOnStaticMismatch:['old']},{dynamic:[failed],cache:{models:[spec('a',{contextWindow:900000}),spec('old'),spec('keep')],updatedAt:999999,authoritative:true,fingerprint:'old'}});
 add('authority-static-change',{...base,dynamicModelsAuthoritative:true},{dynamic:[failed],cache:{models:[spec('a',{contextWindow:900000}),spec('keep')],updatedAt:999999,authoritative:true,fingerprint:'old'}});
 add('failure-latest-cache',base,{dynamic:[{...failed,injectLatestCache:{models:[spec('latest')],updatedAt:900000,authoritative:true,fingerprint:'latest'}}],cache:{models:[spec('old')],updatedAt:800000,authoritative:true,fingerprint:'old'},steps:[{strategy:'online'}]});
 add('headers-static-restored',{...base,staticModels:[spec('a',{headers:{Authorization:'secret-static'}})]},{cache:{models:[spec('a',{headers:{Authorization:'secret-static'}})],updatedAt:999999,authoritative:true,matchingFingerprint:true},steps:[{strategy:'offline'}]});
 add('headers-trusted-fallback',{...base,restorableHeaderFallback:{Authorization:'trusted-current'}},{cache:{models:[spec('dynamic',{headers:{Authorization:'trusted-current'}})],updatedAt:999999,authoritative:true,matchingFingerprint:true},steps:[{strategy:'offline'}]});
 add('headers-unrestorable',base,{dynamic:[failed],cache:{models:[spec('dynamic',{headers:{Authorization:'untrusted'}})],updatedAt:999999,authoritative:true,matchingFingerprint:true}});
 cases.push({id:'manager/fingerprint-reference-memo',family:'manager',module:'model-manager',op:'fingerprint',options:{models:[spec('a')],replacement:[spec('changed')]},responses:[]});
 for(const providerId of ['ollama','cursor','litellm','opencode-go','opencode-zen','github-copilot','openrouter','vllm','test'])for(const baseUrl of [undefined,'https://fixture.test:443/path/v1///?ignored=1#fragment','bad URL'])cases.push({id:`factory/cache-id-${providerId}-${baseUrl===undefined?'default':baseUrl==='bad URL'?'bad':'custom'}`,family:'factory',module:'provider-models/cache-provider-id',op:'resolveModelCacheProviderId',options:{providerId,apiKey:'fixture-key',baseUrl},responses:[],env:{LITELLM_BASE_URL:'http://env.test/v1'}});
 for(const[key,suffix]of [['\ud800','high-tail'],['x\ud800y','high-middle'],['\udc00a','low-middle'],['😀','pair']])cases.push({id:`factory/sqlite-wire-${suffix}`,family:'factory',module:'model-cache',op:'sqlite-wire-binding',options:{providerId:key,fingerprint:key,models:[spec(key,{name:'\udc00',headers:{credential:'secret'}})]},responses:[]});
 const factories=['umans','openai','gmiCloud','groq','cerebras','huggingface','nvidia','novita','deepinfra','xai','xaiOAuth','aimlApi','deepseek','zhipuCodingPlan','mistral','openrouter','zenmux','kilo','alibabaCodingPlan','alibabaTokenPlan','vercelAiGateway','kimiCode','venice','baseten','together','coreWeave','bedrockMantle','meta','moonshot','sakana','aiand','abliteration','yoloAuto','qwenPortal','qianfan','cloudflareAiGateway','xiaomi','vllm','nanoGpt'];
 for(const factory of factories)for(const key of [false,true]){
  const entry={id:'fixture-unknown',name:' Live Name ',display_name:' Display ',description:' Raw description ',context_length:65536,max_completion_tokens:4096,max_tokens:2048,context_window:131072,max_output_length:8192,max_output_tokens:512,context_size:32768,max_model_len:32768,contextWindow:8192,maxTokens:8192,context_length_field:'unused',features:['reasoning','function-calling'],supported_features:['reasoning','reasoning_effort','tools'],capabilities:['reasoning','vision'],input_modalities:['text','image'],endpoints:['chat/completions'],status:1,tags:['chat','reasoning','vision','tool-use'],supported_parameters:['tools','tool_choice','reasoning'],reasoning:{supported_efforts:['minimal','high'],default_effort:'high',mandatory:true},think_efforts:{support:true,valid_efforts:['low','high'],default_effort:'high'},supports_thinking_type:'only',supports_image_in:true,protocol:null,pricing:{prompt:'0.000003',completion:'0.000005',input_cache_read:'0.000001',input_cache_write:'0.000002'},pricings:{prompt:[{value:'3'}],completion:[{value:'5'}],input_cache_write_1_h:[{value:'8'}]},metadata:{tags:['chat','reasoning','vision'],context_length:16384,max_tokens:4096,pricing:{input_tokens:2,output_tokens:4,cache_read_tokens:.5}},currency:'usd',input_per_1m:'1.2',output_per_1m:'2.3',reasoning_efforts:['low','high'],reasoning_effort_default:'high'};
  const payload=factory==='umans'?{'fixture-unknown':{display_name:' Umans ',capabilities:{supports_vision:'via-handoff',supports_tools:false,reasoning:{supported:true,levels:['low','max','invalid'],default_level:'max',can_disable:false},context_window:'65536',recommended_max_tokens:'1024'}}}:{data:[entry]};
  cases.push({id:`factory/options-${factory}-${key?'key':'no-key'}`,family:'factory',module:'provider-models/openai-compat',op:'provider-options',factory:`${factory}ModelManagerOptions`,options:{...(key?{apiKey:factory==='alibabaTokenPlan'?'sk-fixture-key':'fixture-key'}:{}),baseUrl:'https://fixture.test/v1',authenticated:key},responses:[{json:payload}],env:{COREWEAVE_PROJECT:' fixture/team '}});
 }
 const devRow=(extra={})=>({name:' Catalog ',tool_call:true,reasoning:true,modalities:{input:['text','image']},cost:{input:'1.2',output:3,cache_read:.1,cache_write:.2},limit:{context:'65536',output:8192},...extra});
 const devData={};for(const descriptor of openai.MODELS_DEV_PROVIDER_DESCRIPTORS){devData[descriptor.modelsDevKey]??={models:{}};for(const[id,extra]of [['fixture-unknown',{}],['anthropic.claude-sonnet-4-5',{}],['gpt-5.6',{}],['gemini-3.7-flash',{provider:{npm:'@ai-sdk/google'}}],['deepseek-v4-flash',{}],['muse-spark-1.3',{provider:{npm:'@ai-sdk/openai'}}],['claude-sonnet-4',{provider:{npm:'@ai-sdk/anthropic'}}],['retired',{status:'deprecated'}],['no-tools',{tool_call:false}]])devData[descriptor.modelsDevKey].models[id]=devRow(extra);}
 cases.push({id:'factory/models-dev-full-descriptors',family:'factory',module:'provider-models/openai-compat',op:'models-dev-map',options:{data:devData},responses:[]});
 const extraFactories=['synthetic','lmStudio','ollama','waferServerless','opencodeGo','opencodeZen','fireworks','firepass'];
 for(const factory of extraFactories)for(const key of [false,true]){
  const entry={id:'fixture-unknown',name:' Live ',context_length:64000,max_completion_tokens:4000,max_tokens:3000,supported_features:['tools','reasoning'],input_modalities:['text','image'],reasoning_parameters:{efforts:['none','high','max']},max_output_length:16000,pricing:{prompt:'$0.00000045',completion:'$0.0000012',input_cache_reads:'$0.0000001'},wafer:{context_length:48000,display_name:' Wafer ',provider:'moonshotai',capabilities:{vision:true,reasoning:true,tools:false},pricing:{input_cents_per_million:125,output_cents_per_million:500,cache_read_cents_per_million:25}}};
  let responses=[{json:{data:[entry]}}];
  if(factory==='lmStudio')responses=[{json:{data:[{id:'fixture-unknown',type:'VLM',state:'loaded',loaded_context_length:8192,max_context_length:128000}]}},...responses];
  if(factory==='ollama')responses.push({json:{model_info:{'fixture.context_length':16384},capabilities:['thinking','vision']}});
  if(factory==='fireworks')responses=[{json:{}},{json:{models:[{name:'accounts/fireworks/models/kimi-k2p7-code',supportsServerless:true,state:'READY',contextLength:1000000,supportsImageInput:true}],nextPageToken:'page 2'}},{json:{models:[{name:'accounts/fireworks/models/glm-5p3',supportsServerless:true,state:'READY',supportsTools:false},{name:'accounts/fireworks/models/ignore',supportsServerless:false}]}}];
  cases.push({id:`factory/options-${factory}-${key?'key':'no-key'}`,family:'factory',module:'provider-models/openai-compat',op:'provider-options',factory:`${factory}ModelManagerOptions`,options:{...(key?{apiKey:'fixture-key'}:{}),baseUrl:'https://fixture.test/v1'},responses});
 }
 const complex=(id,factory,responses,options={},extra={})=>cases.push({id:`factory/${id}`,family:'factory',module:'provider-models/openai-compat',op:'provider-options',factory:`${factory}ModelManagerOptions`,options:{apiKey:'fixture-key',baseUrl:'https://fixture.test/v1',...options},responses,...extra});
 const clineRoster={clinePass:[{id:'cline-pass/glm-5.2'},{id:' cline-pass/ future-subscription '},{id:'cline-pass/future-subscription'},{id:'bad'}],free:[{id:'vendor/future-free:free'},{id:'cline-pass/ignore'},{id:'future-subscription'}]};
 const clineLive={data:[{id:'vendor/future-subscription',name:'Maker: Future subscription',context_length:262144,top_provider:{max_completion_tokens:65536},architecture:{modality:'text+image->text'},supported_parameters:['reasoning'],pricing:{prompt:'0.000003',completion:'0.000006',input_cache_read:'0.000001'}},{id:'vendor/future-free:free',name:'Vendor: Future free (free)',context_length:65536,top_provider:{max_completion_tokens:16384},architecture:{modality:'text->text'},supported_parameters:[]}]};
 for(const key of [false,true])complex(`cline-roster-${key?'key':'no-key'}`,'clinePass',[{json:clineRoster},{json:clineLive}],key?{}:{apiKey:undefined});
 complex('cline-live-failure','clinePass',[{json:clineRoster},{status:503}]);
 complex('cline-http-failure','clinePass',[{status:401},{json:clineLive}],{}, {expectedErrorName:'Error'});
 complex('cline-roster-missing','clinePass',[{json:{free:[]}},{json:clineLive}],{}, {expectedErrorName:'Error'});
 complex('cline-roster-empty','clinePass',[{json:{clinePass:[{id:'bad'},{id:'cline-pass/ '}]}},{json:clineLive}],{}, {expectedErrorName:'Error'});
 const rich=(id,extra={})=>({model_group:id,model_name:`${id} (2x usage)`,supports_vision:false,providers:['openai'],max_input_tokens:200000,max_output_tokens:4000,supported_openai_params:['tools','reasoning_effort'],input_cost_per_token:.000003,output_cost_per_token:.000006,cache_read_input_token_cost:.000001,cache_creation_input_token_cost:.000002,...extra});
 complex('litellm-rich-complete','litellm',[{json:{}},{json:{data:[rich('proxy-a'),rich('all-team-models',{model_name:'all-team-models',providers:[],supports_vision:undefined,max_input_tokens:undefined,max_output_tokens:undefined,supported_openai_params:[],input_cost_per_token:undefined,output_cost_per_token:undefined})]}}]);
 complex('litellm-membership-and-partial','litellm',[{json:{}},{json:[rich('proxy-a',{providers:undefined,supports_vision:undefined,output_cost_per_token:undefined,cache_read_input_token_cost:undefined,cache_creation_input_token_cost:undefined})]},{json:{models:[rich('proxy-a',{providers:['anthropic'],supports_vision:true,max_input_tokens:400000,max_output_tokens:undefined,input_cost_per_token:undefined}),rich('should-not-enter')]}},{status:404},{status:404}]);
 complex('litellm-403-fallback-warning','litellm',[{json:{}},{status:500},{status:403},{status:404},{status:401},{json:{data:[{id:'gpt-5.6',name:'GPT (3× usage)'}]}}],{baseUrl:'https://litellm-warn.test/v1'});
 complex('litellm-401-no-warning','litellm',[{json:{}},{status:401},{status:401},{status:404},{status:404},{json:{data:[{id:'proxy-a'}]}}]);
 const copilotModel={id:'claude-opus-5',name:' Claude Opus 5 ',capabilities:{type:'chat',limits:{max_context_window_tokens:1048576,max_prompt_tokens:100000,max_output_tokens:64000},supports:{vision:true}},billing:{token_prices:{default:{context_max:200000,input_price:500,output_price:2500,cache_price:50},long_context:{context_max:1000000,input_price:1000,output_price:4000,cache_price:100}}}};
 complex('copilot-custom-context-tiers','githubCopilot',[{json:{data:[copilotModel,{id:'embed',capabilities:{type:'embedding'}}]}}]);
 complex('copilot-real-id-wins','githubCopilot',[{json:{data:[copilotModel,{id:'claude-opus-5-1m',name:'Served'}]}}]);
 complex('copilot-personal-probe','githubCopilot',[{json:{endpoints:{api:'https://api.individual.githubcopilot.com/'}}},{json:{data:[{...copilotModel,capabilities:{...copilotModel.capabilities,supports:undefined}}]}}],{baseUrl:'https://api.githubcopilot.com'});
 complex('copilot-key-envelope','githubCopilot',[{json:{data:[copilotModel]}}],{apiKey:JSON.stringify({token:'token-from-envelope',apiEndpoint:'https://copilot-api.enterprise.test/',enterpriseUrl:'ignored.test'}),baseUrl:'https://api.githubcopilot.com'});
 complex('copilot-enterprise-envelope','githubCopilot',[{json:{data:[{id:'gpt-5.6',capabilities:{supports:{vision:false}}}]}}],{apiKey:JSON.stringify({token:'enterprise-key',enterpriseUrl:'https://enterprise.test/path'}),baseUrl:'https://api.githubcopilot.com'});
 complex('opencode-live-lineage','opencodeGo',[{json:{data:[{id:'muse-spark-1.4-contributor'},{id:'deepseek-v4-flash-free'},{id:'glm-5.3-flash'}]}}],{}, {devPayload:{'opencode-go':{models:{'muse-spark-1.4':{tool_call:true,reasoning:true,limit:{context:1000000,output:131072},provider:{npm:'@ai-sdk/openai'}}}}}});
 complex('synthetic-rounding-boundaries','synthetic',[{json:{data:[{id:'round-odd-integer',pricing:{prompt:'4503.599627370497',completion:'4503.599627370495',input_cache_reads:'-0',input_cache_writes:'0.00000045'}}]}}]);
 complex('meta-free-lineage-billing','meta',[{json:{data:[{id:'muse-spark-1.4-free'},{id:'muse-spark-1.4-contributor'},{id:'muse-spark-1.4'}]}}]);
 complex('openrouter-parse-float-coercion','openrouter',[{json:{data:[{id:'array-pricing',pricing:{prompt:[['2.5']],completion:[[-0]],input_cache_read:[null,'4'],input_cache_write:{value:'3'}}},{id:'numeric-negative-zero',pricing:{prompt:-0,completion:Infinity,input_cache_read:-Infinity}}]}}]);
 for(const[name,payload]of [['null-entry',{models:[null]}],['number-one',{models:[{model:7,name:'Numeric'}]}],['number-sort',{models:[{model:7},{model:8}]}],['object-one',{models:[{model:{id:'raw'}}]}],['boolean-one',{models:[{model:true}]}]])complex(`ollama-tags-${name}`,'ollama',[{json:{data:[]}},{json:payload},...Array.from({length:payload.models.length},()=>({json:{model_info:{'arch.context_length':16384}}}))],{},name==='null-entry'||name==='number-sort'?{expectedErrorName:'TypeError'}:{});
 complex('ollama-show-nan-context','ollama',[{json:{data:[{id:'nan-context'}]}},{jsonEncoded:api.encode({model_info:{'arch.context_length':NaN,'arch.num_ctx':65536},capabilities:[]})}]);
 const helper=(id,op,args)=>cases.push({id:`factory/helper-${id}`,family:'factory',module:'provider-models/openai-compat',op:'public-helper',helper:op,argsEncoded:api.encode(args),responses:[]});
 for(const id of ['','  ',' Embedding-model ',' BAAI/bge-m3 ','gpt-5.6','\ud800']){helper(`aiml-${id}`,'isLikelyAimlApiChatModelId',[id]);helper(`silicon-${id}`,'isLikelySiliconFlowChatModelId',[id]);}
 for(const id of ['unknown',' kimi-k3 ','kimi-for-coding','kimi-k2.5'])for(const fallback of [undefined,null,17])helper(`kimi-${id}-${String(fallback)}`,'kimiCodeMaxTokens',fallback===undefined?[id]:[id,fallback]);
 cases.push({id:'factory/public-constants-and-static-arrays',family:'factory',module:'provider-models/openai-compat',op:'public-values',responses:[]});
 for(const[id,timeout]of [['zero',0],['negative',-1],['nan',NaN],['infinite',Infinity],['overflow',2147483648],['fraction',1.75],['fast',20],['caller-signal',1]])cases.push({id:`factory/litellm-retained-signal-${id}`,family:'factory',module:'provider-models/openai-compat',op:'litellm-rich-retained-signals',optionsEncoded:api.encode({api:'openai-completions',provider:'litellm',baseUrl:'https://retained.test/v1',timeoutMs:timeout}),callerSignal:id==='caller-signal',settleMs:id==='fast'?40:0,responses:[{delayMs:id==='fast'?0:20,json:{data:[rich('retained-model')]}}]});
 for(const[mode,headers]of [['record',{Accept:'custom',Authorization:'override',Trace:'record'}],['callback',[{Trace:'first'},undefined,{Trace:'third'}]]])cases.push({id:`factory/simple-headers-${mode}`,family:'factory',module:'provider-models/openai-compat',op:'simple-headers',options:{providerId:'groq',defaultBaseUrl:'https://default.test/v1',apiKey:'fixture-key',baseUrl:'https://simple.test/v1'},mode,headersEncoded:api.encode(headers),responses:Array.from({length:mode==='record'?1:3},()=>({json:{data:[{id:'simple-model'}]}}))});
 const cloud=(id,payload,metadata={},error)=>cases.push({id:`factory/ollama-cloud-${id}`,family:'factory',module:'provider-models/ollama',op:'provider-options',factory:'ollamaCloudModelManagerOptions',options:{apiKey:'fixture-key',baseUrl:'https://fixture.test'},responses:[{json:payload},{jsonEncoded:api.encode(metadata)}],...(error?{expectedErrorName:'TypeError'}:{})});
 cloud('null-entry',{models:[null]}, {},true);cloud('number-one',{models:[{model:7,name:'Numeric'}]}, {},true);cloud('boolean-one',{models:[{model:true}]}, {},true);cloud('object-one',{models:[{model:{id:'raw'}}]}, {},true);cloud('numeric-name',{models:[{model:'plain',name:7}]});cloud('string-capabilities',{models:[{model:'plain'}]},{capabilities:'thinking,vision'});cloud('object-capabilities',{models:[{model:'plain'}]},{capabilities:{thinking:true}},true);cloud('nonstring-thinking',{models:[{model:7}]},{capabilities:['thinking']},true);cloud('null-models',{models:null});cloud('null-payload',null,{},true);cloud('nan-context',{models:[{model:'plain'}]},{model_info:{'arch.context_window':NaN}});cloud('negative-context',{models:[{model:'plain'}]},{model_info:{'arch.context_window':-0}});
 for(const cloud of [false,true])cases.push({id:`factory/ollama-${cloud?'cloud':'local'}-first-rejection-background`,family:'factory',module:cloud?'provider-models/ollama':'provider-models/openai-compat',op:'ollama-first-rejection-background',cloud,options:{apiKey:'fixture-key',baseUrl:'https://fixture.test/v1'},responses:[...(!cloud?[{json:{data:[]}}]:[]),{json:{models:[null,{model:'background'}]}},{json:{model_info:{'arch.context_length':16384}}}]});
 cases.push({id:'factory/catalog-session-fetch-identity',family:'factory',module:'provider-models/openai-compat',op:'catalog-session-fetch-identity',responses:[{json:{catalog:'A'},headers:{etag:'etag-a'}},{status:304},{json:{catalog:'B'},headers:{etag:'etag-b'}},{status:304}]});
 for(const op of ['clampFireworksKimiMaxTokens','clampKimiK27CodeMaxTokens'])for(const value of [null,NaN,Infinity,-Infinity,-0,40000])helper(`${op}-${String(value)}`,op,[op==='clampFireworksKimiMaxTokens'?'kimi-k2':'kimi-k2.7-code',value]);
 cases.push({id:'factory/non-openai-public-values',family:'factory',op:'non-openai-public-values',responses:[]});
 complex('openrouter-encoded-parse-float-coercion','openrouter',[{jsonEncoded:api.encode({data:[{id:'coercion',pricing:{prompt:[['2.5']],completion:[[-0]],input_cache_read:Infinity,input_cache_write:-Infinity}}]})}]);
 complex('openrouter-supported-encoded-coercion','openrouter',[{jsonEncoded:api.encode({data:[{id:'coercion',supported_parameters:['tools'],pricing:{prompt:[['2.5']],completion:[[-0]],input_cache_read:Infinity,input_cache_write:-Infinity}}]})}]);
 cases.push({id:'factory/public-alibaba-base-url',family:'factory',module:'provider-models/openai-compat',op:'public-alibaba-base-url',responses:[]});
 for(const mode of ['map','lazy'])cases.push({id:`factory/reference-resolver-${mode}`,family:'factory',module:'provider-models/bundled-references',op:'reference-resolver',mode,options:{models:[spec('local-reference',{provider:'local',headers:{credential:'trusted'}})],ids:['local-reference','gpt-5.6','unknown-reference','local-reference']},responses:[]});
 return cases;
}

export async function runCase(test,api){
 if(test.family==='factory'){
  if(test.op==='public-helper'){const module=await api.load(test.module);return module[test.helper](...api.decode(test.argsEncoded));}
  if(test.op==='public-alibaba-base-url'){return(await api.load(test.module)).ALIBABA_TOKEN_PLAN_BASE_URL;}
  if(test.op==='reference-resolver'){const module=await api.load(test.module);let calls=0;const models=new Map(test.options.models.map(model=>[model.id,model]));const resolve=module.createReferenceResolver(test.mode==='lazy'?()=>{calls++;return models;}:models);return{callsBefore:calls,models:test.options.ids.map(id=>resolve(id)),callsAfter:calls};}
  if(test.op==='non-openai-public-values'){const special=await api.load('provider-models/special');const cline=await api.load('provider-models/cline-pass');return{DEVIN_STATIC_MODELS:special.DEVIN_STATIC_MODELS,CLINE_PASS_MODEL_METADATA:cline.CLINE_PASS_MODEL_METADATA};}
  if(test.op==='catalog-session-fetch-identity'){const module=await api.load(test.module);const a=(...args)=>api.fetch(...args);const b=(...args)=>api.fetch(...args);return{a1:await module.fetchWellKnownModels(a),a2:await module.fetchWellKnownModels(a),b1:await module.fetchWellKnownModels(b),b2:await module.fetchWellKnownModels(b)};}
  if(test.op==='ollama-first-rejection-background'){const module=await api.load(test.module);let release;const held=new Promise(resolve=>release=resolve);let showStarted=false,showCompleted=false,completed;const done=new Promise(resolve=>completed=resolve);const fetch=async(url,init)=>{const show=String(url).endsWith('/api/show');if(show)showStarted=true;const response=await api.fetch(url,init);if(show){await held;showCompleted=true;completed();}return response;};const options=module[test.cloud?'ollamaCloudModelManagerOptions':'ollamaModelManagerOptions']({...test.options,fetch});let outcome;const pending=options.fetchDynamicModels().then(models=>outcome={status:'ok',models},error=>outcome={status:'error',name:error.name,message:error.message});await Bun.sleep(20);const before={showStarted,showCompletedBeforeRelease:showCompleted,rejectedBeforeRelease:outcome?.status==='error'};release();await done;await pending;return{...before,outcome};}
  if(test.op==='public-values'){const module=await api.load(test.module);const names=['DEEPINFRA_BASE_URL','KIMI_K27_CODE_RECOMMENDED_MAX_TOKENS','KIMI_CODE_DEFAULT_MAX_TOKENS','ANTHROPIC_CURATED_FALLBACK_MODELS','OPENAI_DAYBREAK_CURATED_FALLBACK_MODELS','GMI_CLOUD_STATIC_MODELS','XAI_OAUTH_CURATED_MODELS','ALIBABA_TOKEN_PLAN_STATIC_MODELS','META_MUSE_STATIC_MODELS','BEDROCK_MANTLE_STATIC_MODELS','SAKANA_FUGU_STATIC_MODELS','AIAND_STATIC_MODELS','ABLITERATION_STATIC_MODELS','YOLO_AUTO_STATIC_MODELS'];return Object.fromEntries(names.map(name=>[name,module[name]]));}
  if(test.op==='litellm-rich-retained-signals'){const module=await api.load(test.module);const signals=[];const options=api.decode(test.optionsEncoded);if(test.callerSignal)options.signal=new AbortController().signal;options.fetch=(url,init)=>{signals.push(init?.signal);return api.fetch(url,init);};const models=await module.fetchLiteLLMRichModels(options);if(test.settleMs)await Bun.sleep(test.settleMs);return{models,signals:signals.map(signal=>({present:!!signal,aborted:!!signal?.aborted,reason:signal?.aborted?signal.reason.name:null}))};}
  if(test.op==='simple-headers'){const module=await api.load(test.module);let calls=0;const headers=api.decode(test.headersEncoded);const config={...test.options,fetch:api.fetch,headers:test.mode==='callback'?()=>headers[calls++]:headers};const options=module.createSimpleOpenAICompletionsOptions(test.options.providerId,test.options.defaultBaseUrl,config);const models=[];for(let i=0;i<(test.mode==='callback'?headers.length:1);i++)models.push(await options.fetchDynamicModels());return{providerId:options.providerId,hasDynamic:typeof options.fetchDynamicModels==='function',headerCalls:calls,models};}
  if(test.op==='models-dev-map'){const module=await api.load(test.module);return module.mapModelsDevToModels(test.options.data,module.MODELS_DEV_PROVIDER_DESCRIPTORS);}
  if(test.op==='provider-options'){const module=await api.load(test.module);const options=module[test.factory]({...test.options,fetch:api.fetch});const hasDynamic=typeof options.fetchDynamicModels==='function';const result={providerId:options.providerId,authoritative:!!options.dynamicModelsAuthoritative,cacheProviderId:options.cacheProviderId??null,dropIds:options.dropCachedModelIdsOnStaticMismatch??null,staticModels:options.staticModels??null,hasDynamic,models:hasDynamic?await options.fetchDynamicModels():undefined};if(test.devPayload!==undefined){result.devModels=options.modelsDev.map(test.devPayload,options.providerId);result.devAdditive=options.modelsDev.additiveOnly??null;}return result;}
  if(test.op==='sqlite-wire-binding'){
   const cache=await api.load('model-cache');const{buildModel}=await api.load('build');const dbPath=path.join(api.caseDir,'wire.db');const options=test.options;
   cache.writeModelCache(options.providerId,900,(options.models??[]).map(buildModel),true,options.fingerprint,dbPath,[]);
   const db=new Database(dbPath);const row=db.query('select provider_id,hex(provider_id) as providerHex,static_fingerprint,hex(static_fingerprint) as fingerprintHex,models from model_cache').get();db.close();
   return{row,read:cache.readModelCache(options.providerId,7200000,()=>1000,dbPath)};
  }
  const module=await api.load(test.module);return module[test.op](test.options.providerId,test.options);
 }
 const module=await api.load('model-manager');
 if(test.op==='fingerprint'){
  const models=test.options.models;const before=module.fingerprintStaticModels(models);const authoritative=module.fingerprintStaticModels(models,true);models.splice(0,models.length,...test.options.replacement);
  return{before,authoritative,mutated:module.fingerprintStaticModels(models),newArray:module.fingerprintStaticModels([...models]),empty:module.fingerprintStaticModels([],true)};
 }
 const cache=await api.load('model-cache');const {buildModel}=await api.load('build');let clock=test.options.now??1000000;
 const options={...test.options,cacheDbPath:path.join(api.caseDir,'models.db'),now:()=>{trace.push({hook:'now',value:clock});return clock;}};delete options.additiveOnly;
 const trace=[];let dynamicIndex=0,devIndex=0;let currentDev;
 const staticModels=(options.staticModels??[]).filter(value=>value&&typeof value==='object'&&typeof value.id==='string').map(buildModel);
 const fingerprint=()=>{let fp=module.fingerprintStaticModels(staticModels,options.dynamicModelsAuthoritative);if(options.dropCachedModelIdsOnStaticMismatch?.length)fp+=`:drop:${Bun.hash(options.dropCachedModelIdsOnStaticMismatch.join('\0')).toString(36)}`;return fp;};
 const write=entry=>cache.writeModelCache(options.cacheProviderId??options.providerId,entry.updatedAt??clock,(entry.models??[]).map(buildModel),entry.authoritative??false,entry.matchingFingerprint?fingerprint():entry.fingerprint??'',options.cacheDbPath,staticModels,options.restorableHeaderFallback);
 if(test.cache)write(test.cache);
 if(test.dynamic)options.fetchDynamicModels=async()=>{const entry=test.dynamic[dynamicIndex++]??test.dynamic.at(-1);trace.push({hook:'dynamic',index:dynamicIndex-1});if(entry.injectLatestCache)write(entry.injectLatestCache);if(entry.error){const e=Error(entry.error.message);e.name=entry.error.name;throw e;}return entry.encoded?api.decode(entry.encoded):entry.undefined?undefined:entry.value;};
 if(test.modelsDev)options.modelsDev={additiveOnly:test.options.additiveOnly,fetch:async()=>{currentDev=test.modelsDev[devIndex++]??test.modelsDev.at(-1);trace.push({hook:'modelsDev.fetch',index:devIndex-1});if(currentDev.error){const e=Error(currentDev.error.message);e.name=currentDev.error.name;throw e;}return currentDev.payload;},map:(payload,providerId)=>{trace.push({hook:'modelsDev.map',payload:api.encode(payload),providerId});if(currentDev.mapError){const e=Error(currentDev.mapError.message);e.name=currentDev.mapError.name;throw e;}return currentDev.mapped;}};
 const manager=module.createModelManager(options);const results=[];const snapshots=[];
 for(const step of test.steps??[{}]){if(step.now!==undefined)clock=step.now;results.push(await manager.refresh(step.strategy));snapshots.push(cache.readModelCache(options.cacheProviderId??options.providerId,options.cacheTtlMs??7200000,()=>clock,options.cacheDbPath));}
 return{results,snapshots,trace};
}
