//! `edit` tool (OMP `packages/coding-agent/src/edit/{index,schemas}.ts` and the
//! `EditSession` binding in `crates/pi-natives/src/edit.rs`, at
//! 596f2da7101178214aa27a753529d15e6b7ad91d).
//!
//! The edit engine is the vendored OMP `pi-edit` crate: every mode's parser,
//! matcher, staging, diff and model-facing text. This module is the host
//! part: it builds the session policy, feeds the finished arguments, and owns
//! the file writes (create, update, move, delete), including upstream's
//! "content did not change on disk" guard and the parse-regression warning.
//!
//! Intentional differences (data safety):
//! - Re-encoding a file that is not valid UTF-8 is refused while staging, so
//!   nothing is written (vendored `pi-edit` `FileRead::persist`, marked
//!   `ARA:`). Upstream decodes lossily and writes U+FFFD over every
//!   undecodable byte. Deletes are unaffected.
//! - Hashline `MV` onto an existing file is refused while staging (vendored
//!   patcher, patch mode's wording) unless the payload removed it earlier.
//!   Upstream overwrites it. patch/apply_patch keep their own upstream guard.
//! - A moved file keeps its permission bits (upstream recreates it with the
//!   default mode, dropping an executable bit).
//! - A failure after some files of the call changed names every effect that
//!   already happened (written files, a copied move, a possibly partial
//!   write), so a retry never runs blind.
//!
//! Updates are written in place like upstream (no temp-file rename), which
//! keeps symlinks, hard links and ownership intact.
//!
//! Not ported (open): streamed argument previews (`openArgStream`), LSP
//! write-through (format on write, diagnostics), the auto-repair model pass
//! (the warning variant of its note is kept), plan mode, `local://` and
//! `vault://` targets, ACP bridges, blackbox recording, approval tiers.

use crate::ToolContext;
use ara_agent::{AgentTool, Concurrency, ToolError, ToolOutput, UpdateFn};
use ara_ai::{JsonObject, Tool, UserBlock};
use async_trait::async_trait;
use pi_edit::session::SessionConfig;
use pi_edit::{
    ApplyRequest, EditError, EditMode, EditResult, EditWriter, FileOp, Session, WriteRequest, WriteResponse,
};
use serde_json::{Value, json};
use std::path::PathBuf;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

/// Settings defaults `edit.fuzzyMatch`, `edit.fuzzyThreshold`,
/// `edit.enforceSeenLines`, `edit.blockAutoGenerated`.
pub const ALLOW_FUZZY: bool = true;
pub const FUZZY_THRESHOLD: f64 = 0.95;
pub const ENFORCE_SEEN_LINES: bool = false;
pub const BLOCK_AUTO_GENERATED: bool = true;

/// JSON schema per mode (`edit/schemas.ts`).
pub fn parameters(mode: EditMode) -> Value {
    match mode {
        EditMode::Replace => json!({
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "old_string": {"type": "string"},
                "new_string": {"type": "string"},
                "replace_all": {"type": "boolean"}
            },
            "required": ["path", "old_string", "new_string"],
            "additionalProperties": false
        }),
        EditMode::Patch => json!({
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "edits": {"type": "array", "items": {
                    "type": "object",
                    "properties": {
                        "op": {"type": "string", "enum": ["create", "delete", "update"]},
                        "rename": {"type": "string"},
                        "diff": {"type": "string"}
                    },
                    "additionalProperties": false
                }}
            },
            "required": ["path", "edits"],
            "additionalProperties": false
        }),
        EditMode::Hashline | EditMode::ApplyPatch | EditMode::Sloppy => json!({
            "type": "object",
            "properties": {"input": {"type": "string"}},
            "required": ["input"],
            "additionalProperties": false
        }),
    }
}

/// Writes staged edits to the local filesystem (`EditTool.#write`). Runs on a
/// blocking thread and records each effect as it happens, for failure reports.
struct FsWriter {
    /// Session cwd, for cwd-relative display of move destinations.
    cwd: PathBuf,
    effects: std::sync::Mutex<Vec<String>>,
}

fn io_err(display: &str, e: std::io::Error) -> EditError {
    EditError::Writer(format!("Cannot write {display}: {e}"))
}

impl FsWriter {
    fn effect(&self, what: String) {
        self.effects.lock().unwrap_or_else(|e| e.into_inner()).push(what);
    }

    fn effects(&self) -> Vec<String> {
        self.effects.lock().unwrap_or_else(|e| e.into_inner()).clone()
    }

    /// In-place write; a failure after the file was opened may leave it
    /// truncated or partial, which is reported as an effect.
    fn write_file(&self, path: &std::path::Path, display: &str, content: &str) -> EditResult<()> {
        std::fs::write(path, content).map_err(|e| {
            if path.exists() {
                self.effect(format!("{display} (write failed; may be truncated or partial)"));
            }
            io_err(display, e)
        })
    }

    fn write_sync(&self, request: &WriteRequest) -> EditResult<WriteResponse> {
        let display = request.display.as_str();
        if request.op == FileOp::Delete {
            std::fs::remove_file(&request.absolute).map_err(|e| io_err(display, e))?;
            self.effect(format!("{display} (deleted)"));
            return Ok(WriteResponse::default());
        }
        let Some(content) = &request.content else {
            return Err(EditError::Writer(format!("Native edit {} request omitted content", request.op.as_str())));
        };
        if let Some(dest) = &request.move_to {
            let dest_display = crate::paths::format_path_relative_to_cwd(dest, &self.cwd, false);
            let mode = std::fs::metadata(&request.absolute).ok().map(|m| m.permissions());
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent).map_err(|e| io_err(&dest_display, e))?;
            }
            self.write_file(dest, &dest_display, content)?;
            if let Some(mode) = mode {
                let _ = std::fs::set_permissions(dest, mode);
            }
            if let Err(e) = std::fs::remove_file(&request.absolute) {
                self.effect(format!("{dest_display} (moved copy written; source {display} not removed)"));
                return Err(io_err(display, e));
            }
            self.effect(format!("{display} (moved to {dest_display})"));
            return Ok(WriteResponse { written: content.clone(), diagnostics_json: None });
        }
        let mut before: Option<Vec<u8>> = None;
        if request.op == FileOp::Update {
            match std::fs::read(&request.absolute) {
                Ok(bytes) => before = Some(bytes),
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
                Err(e) => return Err(io_err(display, e)),
            }
        } else if request.op == FileOp::Create
            && let Some(parent) = request.absolute.parent()
        {
            std::fs::create_dir_all(parent).map_err(|e| io_err(display, e))?;
        }
        self.write_file(&request.absolute, display, content)?;
        self.effect(display.to_string());
        if let Some(before) = before
            && before != content.as_bytes()
        {
            let after = match std::fs::read(&request.absolute) {
                Ok(bytes) => Some(bytes),
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
                Err(e) => return Err(io_err(display, e)),
            };
            if after.as_deref() == Some(before.as_slice()) {
                return Err(EditError::Writer(format!(
                    "edit appeared successful but file content did not change on disk: {display}"
                )));
            }
        }
        Ok(WriteResponse { written: content.clone(), diagnostics_json: None })
    }
}

#[async_trait]
impl EditWriter for FsWriter {
    async fn write(&self, request: WriteRequest) -> EditResult<WriteResponse> {
        self.write_sync(&request)
    }
}

/// A failure message naming what already changed on disk.
fn with_effects(message: String, effects: &[String]) -> String {
    if effects.is_empty() {
        message
    } else {
        format!(
            "{message}\n\nAlready changed on disk by this edit before the failure (re-read before retrying): {}",
            effects.join(", ")
        )
    }
}

pub struct EditTool {
    pub ctx: ToolContext,
}

impl EditTool {
    pub fn new(ctx: ToolContext) -> Self {
        EditTool { ctx }
    }

    fn config(&self) -> SessionConfig {
        SessionConfig {
            mode: self.ctx.edit_mode(),
            policy: pi_edit::PathPolicy {
                cwd: self.ctx.cwd.clone(),
                home_dir: std::env::var_os("HOME").map(PathBuf::from).unwrap_or_default(),
                local_sandbox_root: None,
                vault_roots: None,
                plan_active: false,
                block_auto_generated: BLOCK_AUTO_GENERATED,
            },
            allow_fuzzy: ALLOW_FUZZY,
            fuzzy_threshold: FUZZY_THRESHOLD,
            enforce_seen_lines: ENFORCE_SEEN_LINES,
            raw_input: false,
        }
    }
}

fn file_details(file: &pi_edit::FileOutcome) -> Value {
    let mut d = json!({
        "path": file.move_to.as_ref().unwrap_or(&file.absolute).to_string_lossy(),
        "diff": file.diff,
        "op": file.op.as_str(),
    });
    if let Some(line) = file.first_changed_line {
        d["firstChangedLine"] = json!(line);
    }
    if let Some(dest) = &file.move_to {
        d["move"] = json!(dest.to_string_lossy());
        d["sourcePath"] = json!(file.absolute.to_string_lossy());
    }
    if let Some(old) = &file.old_text {
        d["oldText"] = json!(old);
    }
    if let Some(new) = &file.new_text {
        d["newText"] = json!(new);
    }
    if file.snapshots_pruned {
        d["snapshotsPruned"] = json!(true);
    }
    if !file.warnings.is_empty() {
        d["warnings"] = json!(file.warnings);
    }
    d
}

/// `aggregateDetails` with the multi-file snapshot budget (`capPerFileSnapshots`).
fn details(files: &[pi_edit::FileOutcome]) -> Option<Value> {
    match files {
        [] => None,
        [one] => Some(file_details(one)),
        many => {
            let mut remaining = pi_edit::session::MAX_EDIT_SNAPSHOT_TEXT_CHARS;
            let per_file: Vec<Value> = many
                .iter()
                .map(|f| {
                    let mut d = file_details(f);
                    let kept = f.old_text.as_deref().map_or(0, pi_edit::text::utf16_len)
                        + f.new_text.as_deref().map_or(0, pi_edit::text::utf16_len);
                    if kept > 0 {
                        if kept <= remaining {
                            remaining -= kept;
                        } else if let Some(obj) = d.as_object_mut() {
                            obj.remove("oldText");
                            obj.remove("newText");
                            obj.insert("snapshotsPruned".into(), json!(true));
                        }
                    }
                    d
                })
                .collect();
            let diff = many.iter().map(|f| f.diff.as_str()).filter(|d| !d.is_empty()).collect::<Vec<_>>().join("\n");
            let first = many.iter().find_map(|f| f.first_changed_line);
            Some(json!({"diff": diff, "firstChangedLine": first, "perFileResults": per_file}))
        }
    }
}

#[async_trait]
impl AgentTool for EditTool {
    fn definition(&self) -> Tool {
        Tool {
            name: "edit".into(),
            description: pi_edit::description(self.ctx.edit_mode()).into(),
            parameters: parameters(self.ctx.edit_mode()),
        }
    }

    fn concurrency(&self, _args: &JsonObject) -> Concurrency {
        Concurrency::Exclusive
    }

    async fn execute(
        &self,
        _id: &str,
        args: JsonObject,
        cancel: CancellationToken,
        _update: UpdateFn,
    ) -> Result<ToolOutput, ToolError> {
        if cancel.is_cancelled() {
            return Err(ToolError("Edit was aborted".into()));
        }
        let config = self.config();
        let store = self.ctx.edit_store.clone();
        let args_json = Value::Object(args).to_string();
        // Staging reads files and parses them with tree-sitter; keep it off the
        // async workers like the other file tools. The writer outlives the
        // task so its effects survive a panic.
        let writer = Arc::new(FsWriter { cwd: self.ctx.cwd.clone(), effects: Default::default() });
        let task_writer = Arc::clone(&writer);
        let joined = tokio::task::spawn_blocking(move || {
            let mut session = Session::new(config, store);
            session.set_args_json(&args_json);
            session.finish();
            futures::executor::block_on(session.apply(ApplyRequest::default(), task_writer.as_ref()))
        })
        .await;
        let outcome = match joined {
            Ok(Ok(outcome)) => outcome,
            // Engine and writer failures are model-facing error results.
            Ok(Err(e)) => return Ok(ToolOutput::error(with_effects(e.to_string(), &writer.effects()))),
            Err(e) => return Ok(ToolOutput::error(with_effects(format!("Edit failed: {e}"), &writer.effects()))),
        };
        let mut content = vec![UserBlock::text(outcome.text.clone())];
        let notes: Vec<String> = outcome
            .files
            .iter()
            .filter(|f| f.parse_regressed && f.old_text.is_some() && f.new_text.is_some())
            .map(|f| {
                let path = f.move_to.as_ref().unwrap_or(&f.absolute);
                let rel = crate::paths::relative_path(&self.ctx.cwd, path);
                let display = if rel.is_empty() { path.to_string_lossy().into_owned() } else { rel };
                format!(
                    "Warning: {display} no longer parses after this edit. The change was applied; re-read the edited region and fix the syntax, or revert if unintended."
                )
            })
            .collect();
        if !notes.is_empty() {
            content.push(UserBlock::text(notes.join("\n\n")));
        }
        Ok(ToolOutput { content, details: details(&outcome.files), is_error: false })
    }
}
